[project]
name = "nvx-simulations"
version = "0.1.0"
description = "My playground for various simulation scenarios."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.5",
    "mesa>=3.2.0",
    "seaborn>=0.13.2",
]
